TASK-2248 Class Rails Provider 구현
team-monolith-product/cloud-file-manager pull request #1
Opened 2024-12-06 03:07 UTC by paulkim3151

2024-12-09 05:53 UTC, paulkim3151 commented on .prettierrc
레포지토리가 eslint를 formatter로 이용하는데, 이게 너무 안예뻐서, 
prettier를 formatter로 사용하되, 기존 eslint 설정에 위배되지 않도록 prettierrc 설정을 했습니다.

2024-12-09 05:54 UTC, paulkim3151 commented on src/assets/examples/class-rails.html
이 레포지토리에서 `npm start` 해서 테스트하는 파일에서 사용할 class-rails 테스트 페이지를 추가

2024-12-09 05:55 UTC, paulkim3151 commented on src/code/client.ts
> +
저희 서비스에서 '서버 (class rails 서버)' 이외의 다른 곳에 저장하는 것은 의도되지 않습니다. (로컬에 저장하는 케이스는 `exportFile` 함수로 처리)
따라서 모든 케이스에 대해서 save할때 classRails provider를 사용하도록 수정하였습니다.

2024-12-09 05:56 UTC, paulkim3151 commented on src/code/utils/lang/ko.json
> +  "~URL_TAB.DROP_URL_HERE": "아래에 URL을 입력하세요.",
씨마스 요구사항

2024-12-09 06:48 UTC, paulkim3151 commented on .prettierrc
레포지토리가 eslint를 formatter로 이용하는데, 이게 너무 안예뻐서,
prettier를 formatter로 사용하되, 기존 eslint 설정에 위배되지 않도록 prettierrc 설정을 만들었습니다.

2024-12-09 06:49 UTC, paulkim3151 commented on src/assets/examples/class-rails.html
이 레포지토리에서 `npm start` 실행으로 테스트하는 파일에서 사용할 class-rails 테스트 페이지를 추가

2024-12-13 01:57 UTC, a3626a reviewed
await 처리는 of 때 좀 더 볼게요

2024-12-13 01:57 UTC, a3626a commented on src/code/providers/class-rails-provider.ts
> +      }
무엇을 염두한 예외처리인가요?

2024-12-13 02:23 UTC, paulkim3151 commented on src/code/providers/class-rails-provider.ts
> +      }
네트워크 요청 코드가 있으니 의례적으로 try...catch 구문을 넣은거긴합니다...만 불필요할까요?

2024-12-13 04:57 UTC, a3626a requested changes

2024-12-13 04:57 UTC, a3626a commented on src/code/client.ts
> +    console.log("save client")
지워주세요

2024-12-13 04:57 UTC, a3626a commented on src/code/providers/class-rails-provider.ts
> +      }
알겠습니다

2024-12-16 05:22 UTC, a3626a approved these changes

2024-12-17 07:50 UTC, merged