TASK-2250 코답 OF (CFM)
team-monolith-product/cloud-file-manager pull request #2
Opened 2024-12-10 07:32 UTC by paulkim3151

2024-12-16 09:02 UTC, a3626a approved these changes
reload는 hash에서 읽어서 함.
load는 hash를 업데이트하고 읽음.

이 정도 미묘한 차이가 맞죠? 하나로 통일할 수 없었던 이유를 간단히 설명해주실 수 있을까요?

2024-12-16 09:02 UTC, a3626a commented on src/code/client.ts
> +            callback(metadata.providerData?.projectDataUpdatedAt)
`callback: OpenProviderFileCallback = null`
이 어떻게 가능한가요? ts 관점의 이야기인데... nullable 한건가요 아닌건가요.

2024-12-17 00:46 UTC, paulkim3151 commented
@a3626a 

reload와 loadProject에 대해:
첫 구현에서는 구현방식이 달랐는데 리팩토링 하다보니 결국 로직이 비슷해졌네요.

이것을 호출하는 곳(Codle)에서는 reload와 loadProject가 구분되어있는게 좋다고 생각하긴했습니다.
loadProject 메시지만 남긴다면, 
reload를 하기 위해 이미 열려있는 동일한 프로젝트id로 loadProject 오퍼레이션을 호출하는게 조금은 논리적으로 어색해서요.

구현하는 쪽(CFM)에서는 다른 type의 message를 받더라도 로직을 통일하는 것이 가능은 해보이긴 합니다만, 살짝 미묘합니다.
reload는 굳이 hash를 업데이트 할 필요가 없기 때문에요.
중복되는 로직도 그렇게 복잡한 로직이 아니라서, (openProvider 함수를 호출하기 위한 전처리)
그래서 괜찮다고 생각했습니다.

2024-12-17 00:51 UTC, paulkim3151 commented on src/code/client.ts
> +            callback(metadata.providerData?.projectDataUpdatedAt)
이건 이 레포지토리의 다른 convention을 따른것이긴합니다.

좀 찾아보니, tsconfig 속성 중 `strict`, `strictNullChecks` 옵션이 false이면, 
null은 모든 타입에 암묵적으로 할당가능하다고 하네요. 이 속성들(`strict`, `strictNullChecks`)의 기본값은 false이고요.

2024-12-17 00:55 UTC, a3626a commented on src/code/client.ts
> +            callback(metadata.providerData?.projectDataUpdatedAt)
그럼 callback이 nullable한게 맞으니 null 처리가 필요해보입니다.

2024-12-17 00:55 UTC, a3626a requested changes
callback null 처리 필요

2024-12-17 01:08 UTC, a3626a approved these changes

2024-12-17 07:51 UTC, merged