TASK-2392 프로젝트를 파일로 저장하고 불러오기
team-monolith-product/cloud-file-manager pull request #5
Opened 2024-12-18 08:59 UTC by paulkim3151

### save
directUpload API를 사용하여 projectData 값을 업로드한다음 얻어온 blob_id를 서버에 PUT 요청으로 전송합니다.

### load
url 속성 값을 fetch하여 projectData를 얻어옵니다.
url 속성이 null이면 null 자체를 반환합니다.

2024-12-20 02:03 UTC, paulkim3151 commented on src/code/providers/class-rails-provider.ts
> +    const isEditMode = urlParams.get("mode") === "edit"
OF 과업에서 누락된 부분입니다

2024-12-22 08:11 UTC, a3626a requested changes

2024-12-22 08:11 UTC, a3626a commented on package.json
> +    "@rails/activestorage": "^8.0.100",
버전이 너무 높아요. 현재 BE 버전을 고려한다면 7.x 가 맞다고 생각됩니다.

2024-12-22 08:11 UTC, a3626a commented on src/code/providers/class-rails-provider.ts
> +      await this._updateProject(this._projectId, blob.signed_id)
이 blob을 얻는 로직이 updateProject에 있을 수도 있고 save에 있을 수도 있겠네요. 어떤 관점으로 분리하셨나요?

2024-12-25 23:53 UTC, paulkim3151 commented on package.json
> +    "@rails/activestorage": "^8.0.100",
main-react 쪽 버전이 6.1.6이서 이걸로 맞추겠습니다

2024-12-26 00:02 UTC, paulkim3151 commented on src/code/providers/class-rails-provider.ts
> +      await this._updateProject(this._projectId, blob.signed_id)
음.. 기준을 두고 분리했다기 보다는, 기존 코드에서 변경하기 용이한 방법으로 코드를 수정했습니다

2024-12-26 02:24 UTC, a3626a commented on package.json
> +    "@rails/activestorage": "^8.0.100",
7.x 가 맞는게. main-react도 느린거에요. rails 버전 따라가야해서요

2024-12-26 02:37 UTC, paulkim3151 commented on package.json
> +    "@rails/activestorage": "^8.0.100",
으헉 7.x로 가겠습니다.

2024-12-26 04:54 UTC, a3626a approved these changes

2024-12-30 08:01 UTC, merged